spring:
  profiles:
    active: ${PROFILE}
    group:
      local: local, common, secret
      dev: dev, common, secret
      prod: prod, common, secret

server:
  env: dev

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  serverAddress: ${EC2_PUBLIC_IP}

serverName: dev_server

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  serverAddress: ${EC2_PUBLIC_IP}

serverName: prod_server

---

spring:
  config:
    activate:
      on-profile: common

file:
  path: ${FILE_PATH}
