jwt:
  secret: ${JWT_SECRET} # JWT 서명에 사용할 비밀키
  access-token:
    expiration: ${EXPIRED_ACCESS}  # 30분 (단위: 밀리초)
  refresh-token:
    expiration: ${EXPIRED_REFRESH}  # 7일 (단위: 밀리초)
  header-authorization: ${JWT_HEADER}

spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME}
          account-key: ${AZURE_STORAGE_ACCOUNT_KEY}
